#!/usr/bin/env python3
"""Enrich metadata.json with user-facing keywords and queries.

Adds plain-language queries (EN+RU) and everyday keywords to sections
whose metadata is empty or FPF-jargon-only. Idempotent — safe to re-run.

Usage:
    python3 scripts/enrich_metadata.py
"""

import json
from pathlib import Path

METADATA_PATH = Path("sections/metadata.json")

# User-facing enrichments for sections with weak metadata.
# Generated by analyzing which real user queries fail to find the right sections.
ENRICHMENTS = [
    {
        "pattern_id": "F.1",
        "add_keywords": ["domain survey", "field mapping", "landscape analysis"],
        "add_queries": [
            "How to map out all the disciplines relevant to my project?",
            "How do I avoid tunnel vision when different teams use different terminology?",
            "What fields should I survey before unifying concepts across teams?",
            "Как составить карту предметных областей для проекта?",
            "Как избежать зацикленности на одном стандарте при анализе домена?",
            "Какие области знаний нужно охватить перед объединением терминологии?",
        ],
    },
    {
        "pattern_id": "F.2",
        "add_keywords": ["glossary building", "vocabulary extraction", "naming conventions"],
        "add_queries": [
            "How do I collect and standardize terms from a technical document?",
            "How to create a consistent glossary for one team or domain?",
            "How to stop people using the same word to mean different things?",
            "Как собрать и упорядочить термины из технического стандарта?",
            "Как создать глоссарий для одной команды или домена?",
            "Как бороться с тем что одно слово значит разное в разных отделах?",
        ],
    },
    {
        "pattern_id": "A.19.CN",
        "add_keywords": ["measurement governance", "dashboard consistency", "cross-team reporting"],
        "add_queries": [
            "How to make sure different teams measure things the same way?",
            "How to govern metrics so dashboards across departments are comparable?",
            "How to prevent hidden changes in how numbers are calculated?",
            "Как убедиться что разные команды измеряют показатели одинаково?",
            "Как управлять метриками чтобы дашборды разных отделов были сравнимы?",
            "Как предотвратить скрытые изменения в способе расчёта показателей?",
        ],
    },
    {
        "pattern_id": "A.2.5",
        "add_keywords": ["readiness check", "eligibility tracking", "role lifecycle",
                         "definition of done", "completion criteria", "task readiness"],
        "add_queries": [
            "How to track whether someone is ready and authorized to perform a task?",
            "How to define when a role is active, suspended, or expired?",
            "How to separate 'has the credential' from 'is fit to act right now'?",
            "What does 'done' mean for a task or role?",
            "Как отслеживать готовность и допуск человека к выполнению задачи?",
            "Как определить когда роль активна, приостановлена или истекла?",
            "Как разделить 'имеет допуск' и 'готов действовать прямо сейчас'?",
            "Что значит 'готово' для задачи или роли?",
        ],
    },
    {
        "pattern_id": "A.19",
        "add_keywords": ["multi-dimensional tracking", "system condition", "measurable properties"],
        "add_queries": [
            "How to define all the measurable properties of a system in one place?",
            "How to track a system's condition across multiple dimensions consistently?",
            "How to avoid mixing incompatible units or scales when comparing system states?",
            "Как определить все измеримые свойства системы в одном месте?",
            "Как отслеживать состояние системы по нескольким параметрам одновременно?",
            "Как избежать смешения несовместимых единиц или шкал при сравнении состояний?",
        ],
    },
    {
        "pattern_id": "A.19.CPM",
        "add_keywords": ["comparison", "choose between alternatives", "evaluate options",
                         "framework selection", "decision making"],
        "add_queries": [
            "How to compare two or more approaches fairly?",
            "How to choose between competing alternatives for a project?",
            "How to evaluate frameworks or tools against each other?",
            "Как честно сравнить два или более подхода?",
            "Как выбрать между конкурирующими вариантами для проекта?",
            "Как оценить фреймворки или инструменты относительно друг друга?",
        ],
    },
    {
        "pattern_id": "F.8",
        "add_keywords": ["concept reuse", "new vs existing", "type creation decision"],
        "add_queries": [
            "When should I create a new concept instead of reusing an existing one?",
            "How to avoid creating too many overlapping terms?",
            "Decision guide: new term or reuse?",
            "Когда создавать новое понятие, а когда переиспользовать существующее?",
            "Как избежать создания слишком многих перекрывающихся терминов?",
            "Руководство: новый термин или переиспользование?",
        ],
    },
]


def main():
    metadata = json.loads(METADATA_PATH.read_text(encoding="utf-8"))

    applied = 0
    for enrichment in ENRICHMENTS:
        pid = enrichment["pattern_id"]
        if pid not in metadata:
            print(f"  SKIP: {pid} not found in metadata")
            continue

        entry = metadata[pid]
        existing_kw = set(entry.get("keywords", []))
        existing_q = set(entry.get("queries", []))

        new_kw = [k for k in enrichment.get("add_keywords", []) if k not in existing_kw]
        new_q = [q for q in enrichment.get("add_queries", []) if q not in existing_q]

        if new_kw:
            entry["keywords"] = entry.get("keywords", []) + new_kw
        if new_q:
            entry["queries"] = entry.get("queries", []) + new_q

        if new_kw or new_q:
            applied += 1
            print(f"  {pid}: +{len(new_kw)} keywords, +{len(new_q)} queries")

    METADATA_PATH.write_text(
        json.dumps(metadata, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"\nEnriched {applied} sections. Saved to {METADATA_PATH}")


if __name__ == "__main__":
    main()
